-- Add nutrition columns to all relevant tables
ALTER TABLE bases
  ADD COLUMN IF NOT EXISTS protein_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fat_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carbs_grams REAL DEFAULT 0;

ALTER TABLE milks
  ADD COLUMN IF NOT EXISTS protein_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fat_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carbs_grams REAL DEFAULT 0;

ALTER TABLE syrups
  ADD COLUMN IF NOT EXISTS protein_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fat_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carbs_grams REAL DEFAULT 0;

ALTER TABLE toppings
  ADD COLUMN IF NOT EXISTS protein_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fat_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carbs_grams REAL DEFAULT 0;

ALTER TABLE sizes
  ADD COLUMN IF NOT EXISTS protein_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fat_grams REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carbs_grams REAL DEFAULT 0;
